server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: wdf
    password: 123456
    schema: classpath:init.sql
    data: classpath:insert.sql

  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update